# Generated by Django 4.1.7 on 2023-03-13 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.IntegerField()),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_category', models.CharField(max_length=50)),
                ('nr_employee', models.IntegerField()),
                ('shop_floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.FloatField()),
                ('product_pieces', models.IntegerField()),
                ('product_color', models.CharField(max_length=30)),
                ('product_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.shoppingcenter')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_firstname', models.CharField(max_length=50)),
                ('employee_lastname', models.CharField(max_length=50)),
                ('employee_salary', models.FloatField()),
                ('employee_age', models.IntegerField()),
                ('employee_phone', models.IntegerField()),
                ('employee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.shoppingcenter')),
            ],
        ),
    ]
