# Generated by Django 4.1.7 on 2023-03-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_shop',
        ),
    ]
