# Generated by Django 4.1.7 on 2023-03-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_shoppingcenter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app1.shoppingcenter'),
        ),
    ]
